In [1]:
import warnings
warnings.filterwarnings("ignore")
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
# Let's build a simple computational graph
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)
# ******************************************************
# The following code creates a tf.Session object and then invokes its run method to
# evaluate the total tensor we created
sess = tf.Session()
print(sess.run(total))
# You can pass multiple tensors to tf.Session.run. The run method transparently
# handles any combination of tuples or dictionaries, as in the following example:
print(sess.run({'ab':(a, b), 'total':total}))
# During a call to tf.Session.run any tf.Tensor only has a single value.
# For example, the following code calls tf.random_uniform to produce a tf.Tensor that
# generates a random 3-element vector (with values in [0,1)):
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

Instructions for updating:
non-resource variables are not supported in the long term


Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)
7.0
{'ab': (3.0, 4.0), 'total': 7.0}
[0.9461417  0.00472951 0.35614395]
[0.39144266 0.84033024 0.70117664]
(array([1.1449807, 1.4314128, 1.3578266], dtype=float32), array([2.1449807, 2.4314127, 2.3578267], dtype=float32))
